# Form implementation generated from reading ui file 'view/login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget


class Ui_LoginForm(QWidget):
    def __init__(self):
        super(Ui_LoginForm, self).__init__()
        self.setupUi(self)

    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(448, 128)
        self.formLayoutWidget = QtWidgets.QWidget(parent=LoginForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 60, 301, 42))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.CodeLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.CodeLineEdit.setObjectName("CodeLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.CodeLineEdit)
        self.label_2 = QtWidgets.QLabel(parent=LoginForm)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loginButton = QtWidgets.QPushButton(parent=LoginForm)
        self.loginButton.setGeometry(QtCore.QRect(320, 65, 71, 31))
        self.loginButton.setObjectName("loginButton")

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.label.setText(_translate("LoginForm", "请输入卡密："))
        self.label_2.setText(_translate("LoginForm", "良匠工具箱"))
        self.loginButton.setText(_translate("LoginForm", "登录"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    LoginForm = QtWidgets.QWidget()
    ui = Ui_LoginForm()
    ui.show()
    sys.exit(app.exec())